name: PR Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  linting_and_type-checking:
    name: Linting, Formatting and Type checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache Node dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm 
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile


      - name: Linting and Formatting checks
        run: yarn run lint

      - name: Type checking
        run: yarn run typecheck

  build:
    name: Build check
    runs-on: ubuntu-latest
    needs: linting_and_type-checking 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Node dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm 
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build